title: Karl Molina
email: karlgmolina@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm Karl! I like to build things, learn things,
  and take photos of things reflected in puddles.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://karlmolina.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: xillionpro
github_username:  karlmolina

# Build settings
theme: minima

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
